dianxiangxu/GPMS

- .classpath
- src/main/java/gpms/DAL/MongoDBConnector.java
- src/main/java/gpms/DAL/UserDAO.java
- src/main/java/gpms/DAL/UserProfileDAO.java
- src/main/java/gpms/model/UserAccount.java
- src/main/java/gpms/model/UserProfile.java
User account and user profiles changed, created test classes
> Commit from 6/8

- src/main/java/gpms/DAL/TestConnectionClass.java
- src/main/java/gpms/DAL/TestUpdateClass.java
- src/main/java/gpms/DAL/TestUserAndAccountCreation.java
> Added test classes

- src/main/java/gpms/model/ComplianceInfo.java
- src/main/java/gpms/model/ConflictOfInterest.java
- src/main/java/gpms/model/CostShareInfo.java
- src/main/java/gpms/model/InvestigatorInfo.java
- src/main/java/gpms/model/PositionDetails.java
- src/main/java/gpms/model/ProjectInfo.java
- src/main/java/gpms/model/ProjectPeriod.java
- src/main/java/gpms/model/ProjectType.java
- src/main/java/gpms/model/Proposal.java
- src/main/java/gpms/model/SponsorAndBudgetInfo.java
- src/main/java/gpms/model/Todo.java
- src/main/java/gpms/model/TypeOfRequest.java
- src/main/java/gpms/model/UniversityCommitments.java
- src/main/java/gpms/model/UserAccount.java
- src/main/java/gpms/model/UserProfile.java
Please update my change for added classes
> change by Hector

- src/main/java/gpms/dao/CustomerDAO.java
- src/main/java/gpms/dao/UserAccountDAO.java
- src/main/java/gpms/dao/UserProfileDAO.java
- src/main/java/gpms/gui/UserEntryExample.java
- src/main/java/gpms/model/UserProfile.java
updated UserAccountDAO and UserEntry test
> updated with UserAccountDAO

- src/main/java/gpms/dao/UserProfileDAO.java
- src/main/java/gpms/model/UserAccount.java
- src/main/java/gpms/model/UserProfile.java
- src/test/java/gpms/dao/test/UserProfileDAOTest.java
Created test class UserProfileDAOTest.java.  Created and edited methods in UserProfileDAO.java to improve search function, tested the ability to search ignoring case.  Believe this to be working, will continue to implement.
> Pull Request 6/10/2015. Tests with userprofiledao, incl creation and sort methods

- src/main/java/gpms/dao/UserAccountDAO.java
- src/main/java/gpms/dao/UserProfileDAO.java
- src/main/java/gpms/model/Address.java
- src/main/java/gpms/model/UserAccount.java
- src/main/java/gpms/model/UserProfile.java
- src/test/java/gpms/dao/test/UserProfileDAOTest.java
- src/test/java/gpms/dao/test/UserReferenceCheckTest.java
- src/test/java/gpms/model/test/UserProfileTest.java
Began working on Address adding to the UserProfile class.
> Fixed some errors in compilation.  

- src/main/java/gpms/model/Address.java
- src/main/java/gpms/model/PositionDetails.java
- src/main/java/gpms/model/UserProfile.java
- src/test/java/gpms/dao/test/CompleteUserCreationTest.java
Created CompleteUserCreationTest.java to test the creation of a new user to make sure db fields are populating.
> Push 6/16/2015

- src/main/java/gpms/dao/UserProfileDAO.java
- src/main/java/gpms/model/UserAccount.java
- src/main/java/gpms/model/UserProfile.java
- src/test/java/gpms/dao/test/CRUDTestForUserProfileAndAccount.java
CRUD Work, commented out some index lines causing issues.
CRUD was able to edit an entry and save it w/o duplicate generation
> CRUD Test for UserProfile created

- src/main/java/gpms/dao/UserProfileDAO.java
- src/test/java/gpms/dao/test/CRUDTestForUserProfileAndAccount.java
CRUD Test work, continued working on $id DB ref stuff.  No resolution yet.
> End of day pr 6/18

- src/main/java/gpms/dao/BaseEntity.java
- src/main/java/gpms/dao/ProposalDAO.java
- src/main/java/gpms/model/AuditLog.java
- src/main/java/gpms/model/InvestigatorInfo.java
- src/main/java/gpms/model/Proposal.java
- src/main/java/gpms/model/UserAccount.java
- src/main/java/gpms/model/UserProfile.java
- src/test/java/gpms/dao/test/ProposalDAOTest.java
- src/test/java/gpms/dao/test/ProposalDAOTest2.java
- src/test/java/gpms/model/test/UserAccountTest.java
> Editing ProposalDAOTest

- src/main/java/gpms/dao/UserProfileDAO.java
Further clarification of methods in UserProfileDAO for use in auditing methods.
> PR from 6/22

- src/main/java/QueryReferenceTest.java
- src/main/java/gpms/dao/ProposalDAO.java
- src/main/java/gpms/dao/UserProfileDAO.java
- src/main/java/gpms/model/Address.java
- src/main/java/gpms/model/ComplianceInfo.java
- src/main/java/gpms/model/ConflictOfInterest.java
- src/main/java/gpms/model/Family.java
- src/main/java/gpms/model/InvestigatorInfo.java
- src/main/java/gpms/model/PositionDetails.java
- src/main/java/gpms/model/ProjectInfo.java
- src/main/java/gpms/model/ProjectLocation.java
- src/main/java/gpms/model/ProjectPeriod.java
- src/main/java/gpms/model/ProjectType.java
- src/main/java/gpms/model/Proposal.java
- src/main/java/gpms/model/SponsorAndBudgetInfo.java
- src/main/java/gpms/model/TypeOfRequest.java
- src/main/java/gpms/model/User.java
- src/main/java/gpms/model/UserAccount.java
- src/main/java/gpms/model/UserProfile.java
- src/test/java/gpms/dao/test/ProposalDAOTest.java
> Added clone methods to classes

- src/main/java/gpms/dao/UserProfileDAO.java
- src/test/java/gpms/dao/test/AuditTest.java
Some changes in lines to UserProfileDAO and AuditTest, just to fix and tweak.
> Minor changes to classes

- src/main/java/gpms/dao/UserAccountDAO.java
- src/main/java/gpms/gui/MainDriverTest.java
MainDriverTest.java created, this should be having near full functionality for the database when it is completed.
As of now, you can log in or register a new user or create a new user, and there should be appropriate catches for things like users not found, passwords not being verified, and other things like that.
> Began working on a program to take a complete run of the database.  W.I.P.

- src/main/java/gpms/application/MainDriverTest.java
- src/main/java/gpms/application/NewUserRegistration.java
- src/main/java/gpms/application/RestMode.java
Moved MainDriverTest.java to a new gpms.application package.  Separated inside classes to external classes.  Continuing to increase functionality.
> PR From 6/26

- policy/TestPolicy.xml
- src/test/java/gpms/accesscontrol/EditUserTest.java
- src/test/java/gpms/dao/test/SuiteForCRUDTest.java
Trying to work on xacml implementation in a couple of test classes I've added.
> Working on a couple of test cases

- src/main/java/gpms/dao/UserProfileDAO.java
- src/test/java/gpms/dao/test/Create100UsersTest.java
Adjusted the Create100UsersTest.java, change final int to adjust numbers to make and created a random grouping of position details
> Modified Create100 test

- src/test/java/gpms/dao/test/Create100UsersTest.java
Create100UsersTest will now create middle and last names. There is a 1/3 chance a profile will not have a middle name.
> Updated Create100 with more name features

- src/test/java/gpms/dao/test/Create100Proposals.java
- src/test/java/gpms/dao/test/Create100UsersTest.java
- src/test/java/gpms/dao/test/SUITECreateXUsersAndProposals.java
Suite implemented, SUITECreateXUsersAndProposals.java will run Create100UsersTest.java then Create100Proposals.java.  Should be working to specification.
> Creation Suite implemented.

- src/main/java/gpms/model/InvestigatorInfo.java
- src/main/java/gpms/model/UserProfile.java
- src/test/java/gpms/dao/test/Create100Proposals.java
Improvements in Create100Proposals, including SponsorAndBudgetInfo object fields, proposals are now numbered, should be equivalent to the user profile number from CreateUsers test
> Ammended Create100Proposals

- src/main/java/gpms/accesscontrol/TestControlClass.java
- src/main/java/gpms/rest/RegistrationService.java
- src/main/webapp/Registration.jsp
- src/main/webapp/js/modules/Language/GPMSUserRegistration.js
omw out the door on Monday afternoon,
> Work continuing on JSP stuff

- src/main/java/gpms/model/ActiveUser.java
- src/main/java/gpms/model/UserProfile.java
- src/main/java/gpms/rest/RegistrationService.java
- src/main/webapp/Registration.jsp
- src/main/webapp/js/RegistrationValidation.js
Errors cleaned up in RegstrationService.java, but haven't tested implementation yet.
> Pull Request 9/16

- src/main/java/gpms/rest/RegistrationService.java
- src/main/webapp/Registration.jsp
Registration.jsp is filling in the fields and it's creating entries in the data base.
Presentation is rough but it looks like it's working so far.
> Registration seems to be working.
